apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  # 使用 Cloudflare 访问，不需要 Ingress

namespace: default # 根据需要修改命名空间

# 可以在这里添加公共标签
commonLabels:
  project: ivy-thoughts
  managed-by: kustomize
